import { Worker } from "../types/worker";

export const MOCK_WORKERS: Worker[] = [
  {
    id: "1",
    name: "Nimal Perera",
    category: "plumber",
    rating: 4.8,
    trustScore: 85,
    jobsCompleted: 120,
    province: "western",
    district: "colombo",
    city: "moratuwa",
  },
  {
    id: "2",
    name: "Sunil Fernando",
    category: "plumber",
    rating: 4.5,
    trustScore: 78,
    jobsCompleted: 90,
    province: "western",
    district: "gampaha",
    city: "negombo",
  },
  {
    id: "3",
    name: "Kamal Silva",
    category: "electrician",
    rating: 4.9,
    trustScore: 92,
    jobsCompleted: 200,
    province: "central",
    district: "kandy",
    city: "kandy",
  },
  {
    id: "4",
    name: "Ruwan Jayasinghe",
    category: "carpenter",
    rating: 4.6,
    trustScore: 80,
    jobsCompleted: 150,
    province: "southern",
    district: "galle",
    city: "galle",
  },
  {
    id: "5",
    name: "Suresh Kumar",
    category: "electrician",
    rating: 4.4,
    trustScore: 72,
    jobsCompleted: 60,
    province: "northern",
    district: "jaffna",
    city: "jaffna",
  },
];
